# Copyright 2025, Shanghai Innovation Institute. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM nvcr.io/nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

LABEL maintainer="SII AI Infra Team"

# base environment
RUN apt update \
    && apt install -y rdma-core ibverbs-providers ibverbs-utils   \
    && apt install -y python3 python3-pip \
    && ln -sf /usr/bin/python3 /usr/bin/python  \
    && python -m pip install -U pip \
    && pip install -U setuptools wheel

# dev tools
RUN apt install -y git cmake ninja-build vim

# python packages
RUN pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu124   \
    && pip install flashinfer-python -i https://flashinfer.ai/whl/cu124/torch2.6/   \
    && pip install flash-attn==2.7.3 --no-build-isolation   \
    && pip install vllm==0.8.5.post1    \
    && pip install accelerate codetiming datasets dill hydra-core pandas wandb loguru tensorboard qwen_vl_utils \
    && pip install 'ray[default]>=2.47.1' \
    && pip install opentelemetry-exporter-prometheus==0.47b0

# apex
RUN git clone https://github.com/NVIDIA/apex.git \
    && cd apex \
    && MAX_JOBS=16 pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./    \
    && cd .. && rm -rf apex

# optional: sglang
RUN pip install 'sglang[all]==0.4.6.post5'    \
    && pip install xgrammar==0.1.18

# siirl
RUN git clone --recursive https://github.com/sii-research/siiRL.git \
    && cd siiRL \
    && pip install . \
    && cd .. && rm -rf siiRL
